include:
  - services/pihole.yaml
  - services/syncthing.yaml
  - services/jellyfin.yaml
  - services/radicale.yaml
  - services/zipline.yaml
  - services/radio.yaml
  - services/gluetun.yaml
  - network/cloudflared.yaml

secrets:
  cloudflared_token:
    file: secrets/cloudflared_token
